name: build macOS
on:
  push:
    tags: ['*']
  workflow_dispatch:

env:
  OUT_PATH: build/tesiraOSC_artefacts/Release

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          # - arch: 'x86_64'
          - arch: 'arm64'
    permissions:
      contents: write
    steps:
      # prepare codebase
      - uses: actions/checkout@v4.1.6

      # prep system
      - name: set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # cmake build
      - name: dependencies
        run: |
          brew install boost
          git submodule update --init
      - name: cmake build - ${{matrix.arch}}
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{matrix.arch}}
          cmake --build build

      # upload
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: macOS_${{ matrix.arch }}
          path: ${{env.OUT_PATH}}/
  upload:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: download

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: download/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
