name: build macOS
on:
  push:
    tags: ['*']
  workflow_dispatch:

env:
  OUT_PATH: build/tesiratel_artefacts/Release

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: 'x86_64'
          - arch: 'arm64'
    permissions:
      contents: write
    steps:
      # prepare codebase
      - uses: actions/checkout@v4.1.6

      # prep system
      - name: set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # cmake build
      - name: dependencies
        run: |
          git submodule update --init
      - name: cmake build - ${{matrix.arch}}
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{matrix.arch}}
          cmake --build build

      # upload
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: macOS_${{ matrix.arch }}
          path: ${{env.OUT_PATH}}/
